[profile.default]
src = "src"
out = "out"
auto_detect_solc = false
solc_version = "0.7.6"
optimizer = true
optimizer_runs = 1000000
remappings = ["@uniswap/v3-core/=src/@uniswap/v3-core/", "@openzeppelin/=src/@openzeppelin/"]
